FROM node:20-alpine
# we need to select base image to run the app
# we want to run js file so we gonna use node runtime from docker hub
# node:20-alpine is light weight version of linux

WORKDIR /app

COPY . .

CMD node hello.js